spring:
  application:
    name: PIMOB
  datasource:
    url: jdbc:postgresql://localhost:5432/pimob?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

serverUrl: http://localhost
springdoc:
  api-docs:
    enabled: true
jwt:
  secret: sua-chave-secreta-deve-ter-pelo-menos-256-bits
